<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<title>后台管理</title>
<?php $this->display("layout/adminCss.phtml");?>
</head>
<body>
<div class="layui-layout layui-layout-admin">
    <?php $this->display("layout/header.phtml");?>
    <div class="layui-side layui-bg-black">
        <?php $this->display("layout/nav.phtml");?>
    </div>
    <div class="layui-body">
        <!-- 内容主体区域 -->
        <div style="padding: 15px;">内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
            内容主体区域<br />
        </div>
    </div>
    <?php $this->display("layout/adminFooter.phtml");?>
</div>
<?php $this->display("layout/adminJs.phtml");?>
</body>
</html>